/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: "us-east-1",
    aws_cognito_identity_pool_id:
        "us-east-1:c8142e66-b2fe-446a-b0ed-cbbbcd1a2720",
    aws_cognito_region: "us-east-1",
    aws_user_pools_id: "us-east-1_yWHK6Djnu",
    aws_user_pools_web_client_id: "bl8ri3tsprsvg6tclka53ko3m",
    oauth: {},
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://g6qw3jof4rflzkmzlff72ikwz4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dqwvcvqz2zhypns6qlbfjq5r7i"
};


export default awsmobile;
